"""Sales responder facade. Copy stays here; SYSTEM_INSTRUCTIONS stay on sales_agent."""

from __future__ import annotations

import html
import json
from typing import Any

from openai import APIError, BadRequestError

from app.channels.channel_profiles import channel_system_hint
from app.commerce.checkout_service import checkout_capabilities
from app.commerce.commerce_context import CommerceConversationState
from app.models import AgentResult, IncomingMessage, SalesInterpretation
from app.ops.turn_runtime import LLMCallBudgetExceeded
from app.sales.discovery import (
    _comparison_clarification_question,
    _comparison_needs_qualification,
    _discovery_state,
    _persona_qualification_question,
)
from app.sales.result_utils import mark_sales_result as _mark_sales_result


def responder_contract(state: CommerceConversationState | None) -> dict[str, Any]:
    """Factual response constraints, independent of the wording generated by GPT."""
    if state is None:
        return {
            "dialogue_phase": None,
            "product_state": "unknown",
            "order_state": "not_created",
        }
    revalidation = state.order_payment_revalidation_status
    if revalidation == "unavailable":
        payment_method_state = "unavailable"
    elif state.selected_payment_option is not None:
        payment_method_state = "available"
    elif state.payment_method_preference:
        payment_method_state = "pending_selection"
    else:
        payment_method_state = "not_selected"
    checkout = checkout_capabilities(state)
    confirmation_required = bool(
        state.pending_action == "awaiting_order_confirmation"
        and state.order_confirmation_status == "pending"
        and state.order_review_version
    )
    return {
        "dialogue_phase": state.dialogue_phase,
        "product_state": "in_cart" if state.cart_items else "missing",
        "payment_method_state": payment_method_state,
        "payment_link_state": (
            "available" if state.order_payment_url
            else "pending" if state.order_id else "not_created"
        ),
        "order_state": "created" if state.order_id else "not_created",
        "order_payment_revalidation_status": revalidation,
        "hosted_payment_supported": bool(
            checkout.get("whatsapp_hosted_payment_supported")
        ),
        "customer_confirmation_required": confirmation_required,
        "payment_payable_total": None,
    }


def deterministic_tray_copy_ready(
    tray_result: AgentResult,
    plan: dict[str, Any] | None,
) -> bool:
    """Keep Tray list/price copy when the LLM would only reword it."""
    if tray_result.safety_reason:
        return False
    products = (tray_result.commercial_data or {}).get("products")
    if not isinstance(products, list) or not products:
        return False
    if not (tray_result.reply_text or "").strip():
        return False
    plan = plan or {}
    intent = str(plan.get("intent") or "")
    goal = str(plan.get("goal") or "")
    presented = bool((tray_result.response_metadata or {}).get("presented_products"))
    if intent in {"recommendation", "product_search", "product_comparison"}:
        return True
    if presented and goal in {"find", "recommend", "discover", "compare", "inspect"}:
        return True
    return False


async def generate_clarification_reply(
    *,
    message: IncomingMessage,
    interpretation: SalesInterpretation,
    recent_turns: list[dict[str, Any]] | None = None,
    context_note: str | None = None,
    used_tray: bool = False,
    discovery_state: dict[str, Any] | None = None,
) -> AgentResult:
    from app.sales_agent import (
        SALES_CLARIFICATION_INSTRUCTIONS,
        _normalize_interpreter_history,
        get_settings,
    )

    settings = get_settings()
    persona_gate = bool(
        isinstance(discovery_state, dict)
        and discovery_state.get("persona_qualification_required")
    )
    persona_question = None
    if persona_gate:
        persona_question = _persona_qualification_question(interpretation, discovery_state)
        if persona_question:
            interpretation = interpretation.model_copy(
                update={
                    "needs_clarification": True,
                    "clarification_question": persona_question,
                    "ready_for_retrieval": False,
                }
            )

    deterministic_question = persona_question or interpretation.clarification_question
    if not deterministic_question or _comparison_needs_qualification(interpretation):
        if _comparison_needs_qualification(interpretation):
            deterministic_question = _comparison_clarification_question(
                message, interpretation
            )
        else:
            deterministic_question = (
                interpretation.clarification_question
                or _persona_qualification_question(interpretation, discovery_state)
            )

    if interpretation.stop_clarification and (deterministic_question or "").strip():
        return _mark_sales_result(
            AgentResult(
                reply_text=html.unescape(deterministic_question.strip()),
                intent="commerce",
                handoff_required=False,
                safety_reason="commerce_clarification",
            ),
            interpretation=interpretation,
            goal=interpretation.goal,
            response_source=(
                "openai" if interpretation._source == "openai" else "deterministic_fallback"
            ),
            used_openai_responder=False,
            used_tray=used_tray,
        )
    if (
        interpretation._source == "openai"
        and interpretation.clarification_question
        and not _comparison_needs_qualification(interpretation)
        and not persona_gate
    ):
        return _mark_sales_result(
            AgentResult(
                reply_text=html.unescape(interpretation.clarification_question.strip()),
                intent="commerce",
                handoff_required=False,
                safety_reason="commerce_clarification",
            ),
            interpretation=interpretation,
            goal=interpretation.goal,
            response_source="openai",
            used_openai_responder=False,
            used_tray=used_tray,
        )
    _clarification_empty_fallback = (
        "Me diz em uma frase o que você busca — marca, modelo ou faixa de investimento."
    )
    if not settings.openai_api_key:
        reply = (deterministic_question or "").strip()
        return _mark_sales_result(
            AgentResult(
                reply_text=reply or (persona_question or "").strip() or _clarification_empty_fallback,
                intent="commerce",
                handoff_required=False,
                safety_reason="commerce_clarification",
            ),
            interpretation=interpretation,
            goal=interpretation.goal,
            response_source="deterministic_fallback",
            used_openai_responder=False,
            used_tray=used_tray,
            fallback_reason="openai_api_key_missing",
        )

    normalized_history = _normalize_interpreter_history(recent_turns)
    persona_runtime = None
    try:
        from app.persona.persona_runtime import get_persona_runtime

        persona_runtime = get_persona_runtime()
    except Exception:
        persona_runtime = None
    persona_blocks: list[str] = [SALES_CLARIFICATION_INSTRUCTIONS]
    if persona_runtime and persona_runtime.enabled:
        policy = (persona_runtime.prompt_policy_block() or "").strip()
        skills = (
            persona_runtime.sales_skills_block(
                max_items=8,
                include_examples=False,
            )
            or ""
        ).strip()
        if policy:
            persona_blocks.append(policy)
        if skills:
            persona_blocks.append(skills)
    request_context = {
        "current_message": message.text,
        "interpretation": interpretation.model_dump(),
        "context_note": context_note,
        "persona_qualification_hint": persona_question,
        "DISCOVERY_STATE": discovery_state
        or _discovery_state(
            interpretation,
            recent_turns,
            message_text=message.text,
        ),
    }
    try:
        from app.llm.openai_errors import OpenAIGatewayError
        from app.llm.openai_gateway import generate_text_output

        clarification_messages = [
            {"role": "system", "content": "\n\n".join(persona_blocks)},
            *normalized_history,
            {"role": "user", "content": json.dumps(request_context, ensure_ascii=False)},
        ]
        text_result = await generate_text_output(
            model=settings.openai_model,
            messages=clarification_messages,
            temperature=0.3,
            call_type="clarification",
        )
        content = text_result.text
        if not content or not content.strip():
            raise ValueError("clarification_response_empty")
        return _mark_sales_result(
            AgentResult(
                reply_text=html.unescape(content.strip()),
                intent="commerce",
                handoff_required=False,
                safety_reason="commerce_clarification",
            ),
            interpretation=interpretation,
            goal=interpretation.goal,
            response_source="openai",
            used_openai_responder=True,
            used_tray=used_tray,
        )
    except (APIError, OpenAIGatewayError, LLMCallBudgetExceeded, ValueError, TypeError) as exc:
        print("[sales.clarification] failed", {"error_type": type(exc).__name__})
        fallback = (
            (deterministic_question or persona_question or "").strip()
            or _clarification_empty_fallback
        )
        return _mark_sales_result(
            AgentResult(
                reply_text=fallback,
                intent="commerce",
                handoff_required=False,
                safety_reason="commerce_clarification",
            ),
            interpretation=interpretation,
            goal=interpretation.goal,
            response_source="deterministic_fallback",
            used_openai_responder=False,
            used_tray=used_tray,
            fallback_reason="clarification_responder_failed",
        )


async def sales_response_with_openai(
    message: IncomingMessage,
    plan: dict[str, Any],
    tray_result: AgentResult,
    interpretation: SalesInterpretation | None = None,
    state: CommerceConversationState | None = None,
    recent_turns: list[dict[str, Any]] | None = None,
) -> AgentResult | None:
    from app.llm.capability_catalog import (
        build_capability_catalog,
        format_capability_catalog_for_prompt,
    )
    from app.sales_agent import (
        SALES_RESPONDER_INSTRUCTIONS,
        _normalize_interpreter_history,
        _sales_recent_turns,
        get_settings,
    )

    settings = get_settings()
    if not settings.openai_api_key or tray_result.safety_reason in {
        "tray_adapter_unavailable", "product_match_failed", "product_not_found",
        "ambiguous_product", "product_context_missing", "coupon_not_found",
        "order_not_found", "order_status_technical_failure",
        "invalid_customer_document", "order_customer_not_confirmed",
        "order_customer_mismatch", "order_customer_lookup_technical_failure",
        "customer_orders_lookup_technical_failure",
        "product_media_link_fallback",
        "product_image_link_fallback",
    }:
        return None
    if (tray_result.commercial_data or {}).get("input_template"):
        return None
    if deterministic_tray_copy_ready(tray_result, plan):
        return _mark_sales_result(
            tray_result,
            interpretation=interpretation,
            goal=plan.get("goal"),
            response_source="deterministic_fallback",
            used_openai_responder=False,
            used_tray=bool(tray_result.response_metadata.get("used_tray", True)),
        )
    try:
        from app.llm.openai_errors import OpenAIGatewayError
        from app.llm.openai_gateway import generate_text_output

        from app.llm.prompt_compiler import (
            legacy_contract_extra_blocks,
            resolve_system_instructions,
        )

        responder_prompt = (
            f"{SALES_RESPONDER_INSTRUCTIONS}\n\n"
            f"{channel_system_hint(message.channel)}\n\n"
            f"{format_capability_catalog_for_prompt()}"
        )
        history_turns = (
            recent_turns
            if recent_turns is not None
            else _sales_recent_turns.get()
        )
        history = _normalize_interpreter_history(history_turns)
        responder_instructions = resolve_system_instructions(
            fallback_instructions=responder_prompt,
            incoming=message,
            conversation_state=state,
            recent_turns=history_turns,
            extra_system_blocks=legacy_contract_extra_blocks(
                responder_prompt,
                tag="sales_responder_contract",
            ),
        )
        memory_sidechannel = bool(
            getattr(settings, "agent_memory_proposals_enabled", False)
            or getattr(settings, "agent_instruction_extension_proposals_enabled", False)
            or getattr(settings, "agent_conversation_summary_enabled", False)
        )
        if memory_sidechannel:
            from app.memory.memory_policy import MEMORY_POLICY_PROMPT

            responder_instructions = (
                f"{responder_instructions}\n\n{MEMORY_POLICY_PROMPT}"
            )

        from app.memory.history_window import resolve_model_history_limit
        from app.memory.working_memory import build_working_memory

        model_history_limit = resolve_model_history_limit(settings)
        responder_messages = [
            {"role": "system", "content": responder_instructions},
            *history[-model_history_limit:],
            {
                "role": "user",
                "content": json.dumps(
                    {
                        "original_message": message.text,
                        "plan": plan,
                        "dialogue_phase": (
                            state.prompt_contract_payload().get("dialogue_phase")
                            if state
                            else None
                        ),
                        "STATE_FACTS": (
                            state.interpreter_payload() if state else {}
                        ),
                        "WORKING_MEMORY": (
                            build_working_memory(state) if state else {}
                        ),
                        "AVAILABLE_CAPABILITIES": build_capability_catalog(),
                        "RESPONSE_CONTRACT": responder_contract(state),
                        "FACTS": tray_result.commercial_data or {"summary": tray_result.reply_text},
                    },
                    ensure_ascii=False,
                ),
            },
        ]

        envelope = None
        content = None
        if memory_sidechannel:
            from app.memory.memory_models import (
                AgentTurnEnvelope,
                AgentTurnReplyEnvelope,
            )
            from app.llm.openai_gateway import parse_structured_output

            try:
                parse_result = await parse_structured_output(
                    model=settings.openai_model,
                    text_format=AgentTurnEnvelope,
                    messages=responder_messages,
                    temperature=0.3,
                    call_type="response_composition_envelope",
                )
                envelope = parse_result.parsed
                content = getattr(envelope, "reply", None) if envelope is not None else None
            except (APIError, OpenAIGatewayError, BadRequestError, ValueError, TypeError):
                print("[sales.responder] envelope_failed_fallback_slim")
                try:
                    slim = await parse_structured_output(
                        model=settings.openai_model,
                        text_format=AgentTurnReplyEnvelope,
                        messages=responder_messages,
                        temperature=0.3,
                        call_type="response_composition_envelope_slim",
                    )
                    content = getattr(slim.parsed, "reply", None)
                except (APIError, OpenAIGatewayError, BadRequestError, ValueError, TypeError):
                    print("[sales.responder] envelope_failed_fallback_text")
                    text_result = await generate_text_output(
                        model=settings.openai_model,
                        messages=responder_messages,
                        temperature=0.3,
                        call_type="response_composition",
                    )
                    content = text_result.text
        else:
            text_result = await generate_text_output(
                model=settings.openai_model,
                messages=responder_messages,
                temperature=0.3,
                call_type="response_composition",
            )
            content = text_result.text
        if not content or not content.strip():
            return None
        final_result = AgentResult(
            reply_text=html.unescape(content.strip()),
            intent="commerce",
            handoff_required=False,
            safety_reason=tray_result.safety_reason,
            commercial_data=tray_result.commercial_data,
            response_metadata=dict(tray_result.response_metadata),
        )
        final_result.response_metadata.setdefault(
            "factual_fallback_text",
            tray_result.reply_text,
        )
        if envelope is not None:
            final_result.response_metadata["agent_turn_envelope"] = envelope.model_dump(
                mode="json"
            )
        return _mark_sales_result(
            final_result,
            interpretation=interpretation,
            goal=plan.get("goal"),
            response_source="openai",
            used_openai_responder=True,
            used_tray=bool(tray_result.response_metadata.get("used_tray", True)),
        )
    except (APIError, OpenAIGatewayError, LLMCallBudgetExceeded, ValueError, TypeError) as exc:
        print("[sales.responder] failed", {"error_type": type(exc).__name__})
        return None
