"""Catalog retrieval: compile probes, filter, rank, revalidate, execute."""

from __future__ import annotations

from app.catalog.retrieval.availability import (
    apply_persona_presentation_order,
    commercial_availability_facts,
    in_ready_to_ship_category,
    product_availability_state,
    product_category_ids,
    ready_to_ship_category_ids,
)
from app.catalog.retrieval.compiler import ProductRetrievalCompiler
from app.catalog.retrieval.hard_filter import hard_filter_products
from app.catalog.retrieval.limits import (
    CANDIDATE_POOL_LIMIT,
    CATALOG_DISCOVERY_MAX_PAGES,
    CATALOG_DISCOVERY_MAX_PRODUCTS,
    CUSTOMER_RESULT_LIMIT,
    GPT_MATCH_CANDIDATE_LIMIT,
    MAX_VARIANT_PRODUCT_QUERIES,
    PRODUCT_PAGE_LIMIT,
    RERANK_SELECTION_LIMIT,
    SEMANTIC_MATCH_POOL_LIMIT,
    ToolExecutor,
    candidate_pool_limit,
    customer_result_limit,
    prefer_ready_stock_enabled,
    rerank_selection_limit,
    revalidate_top_n,
)
from app.catalog.retrieval.price import (
    effective_price,
    resolve_commercial_price,
)
from app.catalog.retrieval.rerank import (
    _deterministic_semantic_order,
    deterministic_semantic_order,
    rerank_products,
)
from app.catalog.retrieval.revalidate import revalidate_products
from app.catalog.retrieval.runtime import get_settings
from app.catalog.retrieval.scoring import (
    compact_candidates,
    exact_progress_matches,
    exact_specific_product_matches,
    infer_family_codes_from_candidates,
    keyword_match_products,
    prefer_dial_and_case_matches,
    prefilter_specific_candidates,
    score_catalog_candidates,
    semantic_preferences,
    soft_confirm_candidates,
    specific_product_search_terms,
)
from app.catalog.retrieval.specific import (
    match_specific_products,
    resolve_products_from_message_text,
)
from app.catalog.retrieval.text import _fold, _product_text, fold_text, product_text
from app.catalog.retrieval.tokens import (
    _DIAL_COLOR_TOKENS,
    _OPTIONAL_MODEL_TOKENS,
    catalog_match_tokens,
    commercial_model_aliases,
    effective_product_reference,
    expand_color_aliases,
    extract_model_codes,
    extract_reference_code,
    identity_core_tokens,
    is_plausible_product_reference,
    is_promaster_sky_pilot_ask,
    is_prospex_diver_ask,
    model_excludes_gmt,
    normalize_pt_catalog_query,
    preference_case_finish_tokens,
    preference_color_search_labels,
    preference_color_tokens,
    preference_feature_tokens,
    preference_gender_tokens,
    product_compatible_with_requested_movement,
    product_conflicts_dial_color,
    product_matches_case_finish_tokens,
    product_matches_color_tokens,
    product_matches_feature_tokens,
    product_matches_gender_tokens,
    rank_products_for_dial_color,
    required_model_tokens,
    significant_model_tokens,
)
from app.catalog.retrieval.types import (
    CommercialPriceResolution,
    ProductMatchError,
    ProductMatchSelection,
    ProductRerankSelection,
    ProductRetrievalPlan,
    ProductRetrievalRequest,
    SpecificProductResolution,
)
from app.catalog.retrieval.variants import enrich_product_variants

__all__ = [
    "CANDIDATE_POOL_LIMIT",
    "CATALOG_DISCOVERY_MAX_PAGES",
    "CATALOG_DISCOVERY_MAX_PRODUCTS",
    "CUSTOMER_RESULT_LIMIT",
    "GPT_MATCH_CANDIDATE_LIMIT",
    "MAX_VARIANT_PRODUCT_QUERIES",
    "PRODUCT_PAGE_LIMIT",
    "RERANK_SELECTION_LIMIT",
    "SEMANTIC_MATCH_POOL_LIMIT",
    "CommercialPriceResolution",
    "ProductMatchError",
    "ProductMatchSelection",
    "ProductRerankSelection",
    "ProductRetrievalCompiler",
    "ProductRetrievalPlan",
    "ProductRetrievalRequest",
    "SpecificProductResolution",
    "ToolExecutor",
    "_DIAL_COLOR_TOKENS",
    "_OPTIONAL_MODEL_TOKENS",
    "_deterministic_semantic_order",
    "_fold",
    "_product_text",
    "apply_persona_presentation_order",
    "candidate_pool_limit",
    "catalog_match_tokens",
    "commercial_availability_facts",
    "commercial_model_aliases",
    "compact_candidates",
    "customer_result_limit",
    "deterministic_semantic_order",
    "effective_price",
    "effective_product_reference",
    "enrich_product_variants",
    "exact_progress_matches",
    "exact_specific_product_matches",
    "expand_color_aliases",
    "extract_model_codes",
    "extract_reference_code",
    "fold_text",
    "get_settings",
    "hard_filter_products",
    "identity_core_tokens",
    "in_ready_to_ship_category",
    "infer_family_codes_from_candidates",
    "is_plausible_product_reference",
    "is_promaster_sky_pilot_ask",
    "is_prospex_diver_ask",
    "keyword_match_products",
    "match_specific_products",
    "model_excludes_gmt",
    "normalize_pt_catalog_query",
    "prefer_dial_and_case_matches",
    "prefer_ready_stock_enabled",
    "preference_case_finish_tokens",
    "preference_color_search_labels",
    "preference_color_tokens",
    "preference_feature_tokens",
    "preference_gender_tokens",
    "prefilter_specific_candidates",
    "product_availability_state",
    "product_category_ids",
    "product_compatible_with_requested_movement",
    "product_conflicts_dial_color",
    "product_matches_case_finish_tokens",
    "product_matches_color_tokens",
    "product_matches_feature_tokens",
    "product_matches_gender_tokens",
    "product_text",
    "rank_products_for_dial_color",
    "ready_to_ship_category_ids",
    "required_model_tokens",
    "rerank_products",
    "rerank_selection_limit",
    "resolve_commercial_price",
    "resolve_products_from_message_text",
    "revalidate_products",
    "revalidate_top_n",
    "score_catalog_candidates",
    "semantic_preferences",
    "significant_model_tokens",
    "soft_confirm_candidates",
    "specific_product_search_terms",
]
