-- Operator-editable catalog evidence and output style controls.
INSERT INTO public.agent_configuration_catalog(key, definition) VALUES
('storefrontHosts', '{"key": "storefrontHosts", "target": "policy", "type": "textarea", "default": "[\"www.newstorerj.com.br\"]", "label": "Domínios oficiais da vitrine", "description": "Lista JSON de domínios oficiais usados na busca e validação do produto.", "group": "Busca por imagem e evidências", "readOnly": false}'::jsonb),
('storefrontImageHosts', '{"key": "storefrontImageHosts", "target": "policy", "type": "textarea", "default": "[\"images.tcdn.com.br\"]", "label": "Domínios das fotos do catálogo", "description": "Lista JSON de domínios públicos autorizados para comparar imagens do catálogo.", "group": "Busca por imagem e evidências", "readOnly": false}'::jsonb),
('storefrontStoreCode', '{"key": "storefrontStoreCode", "target": "policy", "type": "textarea", "default": "687890", "label": "Código da loja na vitrine", "description": "Identificador da loja usado na consulta pública.", "group": "Busca por imagem e evidências", "readOnly": false}'::jsonb),
('imageStorefrontMaxPages', '{"key": "imageStorefrontMaxPages", "target": "policy", "type": "integer", "default": 3, "label": "Páginas por consulta visual", "description": "Limite de páginas da vitrine em cada consulta.", "group": "Busca por imagem e evidências", "readOnly": false, "min": 1, "max": 10}'::jsonb),
('imageStorefrontMaxQueries', '{"key": "imageStorefrontMaxQueries", "target": "policy", "type": "integer", "default": 3, "label": "Consultas por foto", "description": "Limite de reformulações da pesquisa sem novas chamadas ao modelo.", "group": "Busca por imagem e evidências", "readOnly": false, "min": 1, "max": 5}'::jsonb),
('imageStorefrontCandidateLimit', '{"key": "imageStorefrontCandidateLimit", "target": "policy", "type": "integer", "default": 36, "label": "Candidatos por consulta visual", "description": "Quantidade máxima de imagens comparadas por consulta.", "group": "Busca por imagem e evidências", "readOnly": false, "min": 1, "max": 120}'::jsonb),
('imageStorefrontDownloadConcurrency', '{"key": "imageStorefrontDownloadConcurrency", "target": "policy", "type": "integer", "default": 4, "label": "Downloads simultâneos", "description": "Limite de downloads simultâneos das fotos candidatas.", "group": "Busca por imagem e evidências", "readOnly": false, "min": 1, "max": 8}'::jsonb),
('imageStorefrontColorErrorMax', '{"key": "imageStorefrontColorErrorMax", "target": "policy", "type": "number", "default": 0.035, "label": "Diferença máxima de cor da foto", "description": "Erro médio RGB normalizado. Complementa a comparação de contornos para separar variantes.", "group": "Busca por imagem e evidências", "readOnly": false, "min": 0, "max": 0.1, "step": 0.005}'::jsonb),
('imageSearchColorAliases', '{"key": "imageSearchColorAliases", "target": "policy", "type": "textarea", "default": "{\"azul\": \"azul\", \"blue\": \"azul\", \"brown\": \"marrom\", \"marrom\": \"marrom\", \"black\": \"preto\", \"preto\": \"preto\", \"white\": \"branco\", \"branco\": \"branco\", \"green\": \"verde\", \"verde\": \"verde\", \"red\": \"vermelho\", \"vermelho\": \"vermelho\", \"gold\": \"dourado\", \"dourado\": \"dourado\", \"silver\": \"prata\", \"prata\": \"prata\", \"pink\": \"rosa\", \"rosa\": \"rosa\", \"gray\": \"cinza\", \"grey\": \"cinza\", \"cinza\": \"cinza\", \"orange\": \"laranja\", \"laranja\": \"laranja\", \"yellow\": \"amarelo\", \"amarelo\": \"amarelo\"}", "label": "Vocabulário de cores para pesquisa", "description": "Objeto JSON que traduz termos reconhecidos na foto para termos do catálogo.", "group": "Busca por imagem e evidências", "readOnly": false}'::jsonb),
('imageSearchGenericTokens', '{"key": "imageSearchGenericTokens", "target": "policy", "type": "textarea", "default": "[\"automatic\", \"automatico\", \"automatica\", \"chronograph\", \"cronografo\", \"cronografico\", \"watch\", \"relogio\", \"light\", \"dark\", \"claro\", \"escuro\"]", "label": "Termos genéricos da busca visual", "description": "Lista JSON de termos removidos apenas da consulta. Os nomes das famílias são preservados.", "group": "Busca por imagem e evidências", "readOnly": false}'::jsonb),
('responsePlainTextEnabled', '{"key": "responsePlainTextEnabled", "target": "policy", "type": "boolean", "default": true, "label": "Respostas sem asteriscos", "description": "Remove asteriscos do texto final enviado ao cliente.", "group": "Busca por imagem e evidências", "readOnly": false}'::jsonb),
('message.image_catalog_identified', '{"key": "message.image_catalog_identified", "target": "message", "type": "textarea", "default": "Encontrei o produto que corresponde à foto: {name}.\nLink da página conferida: {url}", "label": "Foto confirmada no catálogo", "description": "Exige comparação visual e conferência do identificador da página. Preserve {name} e {url}.", "group": "Busca por imagem e evidências", "readOnly": false}'::jsonb),
('message.image_catalog_identified_unavailable', '{"key": "message.image_catalog_identified_unavailable", "target": "message", "type": "textarea", "default": "Encontrei o produto que corresponde à foto: {name}. Ele consta como indisponível no site neste momento.\nPágina do produto: {url}", "label": "Foto confirmada, indisponível", "description": "A indisponibilidade precisa constar nos dados estruturados do produto. Preserve {name} e {url}.", "group": "Busca por imagem e evidências", "readOnly": false}'::jsonb),
('message.image_catalog_unconfirmed', '{"key": "message.image_catalog_unconfirmed", "target": "message", "type": "textarea", "default": "Ainda não consegui confirmar o produto exato dessa foto no catálogo. Pode enviar uma foto mais próxima do mostrador ou a referência, se você tiver?", "label": "Identidade visual não confirmada", "description": "Resposta quando a busca não reuniu evidência suficiente para identificar uma variante.", "group": "Busca por imagem e evidências", "readOnly": false}'::jsonb),
('message.catalog_link_unverified', '{"key": "message.catalog_link_unverified", "target": "message", "type": "textarea", "default": "Não consegui validar a página desse produto agora. Vou precisar conferir o link antes de enviar.", "label": "Link do produto não validado", "description": "Resposta quando o endereço não abre uma página válida do produto consultado.", "group": "Busca por imagem e evidências", "readOnly": false}'::jsonb)
ON CONFLICT (key) DO UPDATE SET definition=EXCLUDED.definition, updated_at=now();
