create table if not exists public.ai_story_highlight_references (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  tenant_id text not null,
  name text not null check (char_length(btrim(name)) between 2 and 200),
  normalized_name text not null check (char_length(normalized_name) between 1 and 200),
  product_url text not null check (char_length(product_url) between 10 and 2000),
  active boolean not null default true,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workspace_id, tenant_id, normalized_name),
  unique (workspace_id, tenant_id, product_url)
);

create index if not exists ai_story_highlight_references_lookup_idx
  on public.ai_story_highlight_references (workspace_id, tenant_id, active, normalized_name);

alter table public.ai_story_highlight_references enable row level security;
revoke all on table public.ai_story_highlight_references from public, anon, authenticated;
revoke all on sequence public.ai_story_highlight_references_id_seq from public, anon, authenticated;
grant select, insert, update, delete on table public.ai_story_highlight_references to service_role;
grant usage, select on sequence public.ai_story_highlight_references_id_seq to service_role;
